config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'guess#index', as: 'guess'
  get 'guess_game' => 'guess#guess_game', as: 'guess_game'
  get 'guesses' => 'guess#guesses', as: 'guesses'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guess.rb
class Guess < ApplicationRecord
  def self.create_guess(name:, previous_number: nil, next_number: nil, guess: nil, correct: nil)
    new_guess = Guess.new
    new_guess.name = name
    new_guess.previous_number = previous_number
    new_guess.next_number = next_number
    new_guess.guess = guess
    new_guess.correct = correct

    new_guess
  end

  def determine_winning_streak
    guesses = Guess.order(created_at: :desc).where(name: name)
    streak = 0

    guesses.each do |guess|
      return streak unless guess.correct

      streak += 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guess_controller.rb
class GuessController < ApplicationController
  def index
  end

  def guess_game
    guess = params[:guess]
    name = params[:name]

    name ||= guess[:name]
    
    @guess_page = GuessService.create_guess_page(guess, name)
  end

  def guesses
    @guesses = GuessService.retrieve_guesses
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guess_helper.rb
module GuessHelper
end

app/views/guess/guess_game.html.erb
<div class="mx-auto mt-5 w-75">
  <% current_guess = @guess_page.current_guess %>
  <div class="text-center">
    <h1>Guess if the next number is lower or higher</h1>
    <h2>Numbers are between 0 and 100</h2>
  </div>
  <div class="text-center" style="margin-top: 100px">
    <h4>Lower or higher than <%= current_guess.next_number %>?</h4>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-2">
          <%= button_to "Lower",
                        guess_game_path,
                        { :method => :get,
                          params: { :guess => "lower", :name => current_guess.name },
                          :class => "btn btn-primary w-100" }
                        %>
        </div>
        <div class="col-2">
          <%= button_to "Higher",
                        guess_game_path,
                        { :method => :get,
                          params:{ :guess => "higher", :name => current_guess.name },
                          :class => "btn btn-primary w-100" }
          %>
        </div>
      </div>
    </div>
  </div>
  <% unless @guess_page.initial %>
    <div class="text-center mt-5">
      <h4>The number was <%= current_guess.previous_number %> and the next number was <%= current_guess.next_number %>.</h4>
      <h4>You guessed <%= current_guess.guess %>.</h4>
        <% if current_guess.correct %>
          <h3 class="text-success mt-3">
            Correct!
          </h3>
        <% else %>
          <h3 class="text-danger mt-3">
            Wrong!
          </h3>
        <% end %>
    </div>
    <div class="text-center mt-5">
      <h5>Winning streak:</h5>
      <h2><%= @guess_page.winning_streak %></h2>
    </div>
  <% end %>
</div>

app/views/guess/guesses.html.erb
<div class="mx-auto mt-5 w-50">
  <h1 class="text-center">All Guesses</h1>
  <% @guesses.each do |guess| %>
    <% if guess.next_number %>
      <div class="card mb-1 <%= guess.correct ? 'bg-success' : 'bg-danger' %>">
        <div class="card-body">
          <strong>name:</strong> <%= guess.name %>
          <strong>previous number:</strong> <%= guess.previous_number %>
          <strong>next number:</strong> <%= guess.next_number %>
          <strong>guess:</strong> <%= guess.guess %>
          <strong>correct:</strong> <%= guess.correct %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/guess/index.html.erb
  <div class="mx-auto mt-5 w-25">
  <h1 class="text-center mb-3">Guessing game</h1>
  <%= form_for :guess, :html => { :class => 'form-inline', :method => 'get' }, url: guess_game_path do |guess| %>
      <%= guess.label :name %>
      <%= guess.text_field(:name, {:class => 'from-control ml-2'}) %>
      <%= guess.submit('start', { :class => 'btn btn-primary ml-2' }) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guessing Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'bootstrap/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="nav-link navbar-brand" href="#">Github Code</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "All guesses", guesses_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Guessing game", guess_path, :class => "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>